# Generated by Django 6.0.4 on 2026-05-17 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_post_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
